# Generated by Django 3.2.9 on 2021-12-01 16:39

import EventApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EVENT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data', models.DateField()),
                ('Start', models.TimeField()),
                ('End', models.TimeField()),
                ('Price', models.FloatField()),
                ('Code', models.CharField(max_length=12, validators=[EventApp.models.validate_code])),
                ('Location', models.CharField(max_length=70)),
            ],
        ),
    ]
